[general]
# exec commands that take longer than this (in milliseconds) will be terminated
exec-timeout = 1000

[bindings]
[bindings.example-ptt]
keycodes = ["BTN_EXTRA"]
actions = [
    "net.sourceforge.mumble.mumble/startTalking",
]

[bindings.example-ptt-release]
keycodes = ["BTN_EXTRA:RELEASED"]
actions = [
    "dbus:net.sourceforge.mumble.mumble/stopTalking",
]

[bindings.full-example]
keycodes = ["KEY_SPACE", "BTN_RIGHT:released"]
keycode-combos = [
    ["KEY_SPACE", "KEY_LEFTSHIFT"],
    ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_DELETE"],
]
actions = [
    "exec:sleep 10",
]

# /proc/bus/input/devices
# devices = [
#     "my cool keyboard"
# ]
